apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-transport-tls
  namespace: opendistro
spec:
  isCA: true
  duration: 2160h # 90d 2160h
  renewBefore: 168h # 7d 168h
  commonName: es-client
  dnsNames:
    - es-client
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: es-transport-tls
